### ISSUE TITLE
smalt_index error

### ISSUE THREAD

**Issue by kazumaxneo** [bioinfoMMS/EvalDNA#1]
Hi,

It's a great tool.
When I pulled official docker image <bioinfomms/evaldna> and ran it, I got the following error.

[REAPR smaltmap] Running:
/usr/src/app/code/Reapr_1.0.18_for_Evaldna/src/smalt index -k 13 -s 2
out_reapr_../results/flye.bam.tmp.1089.smaltmap.smalt_index
../results/flye.facheck.fa
# Command line:  /usr/src/app/code/Reapr_1.0.18_for_Evaldna/src/smalt
index -k 13 -s 2
out_reapr_../results/flye.bam.tmp.1089.smaltmap.smalt_index
../results/flye.facheck.fa
# Reading sequences ...
# Writing sequence set ...
[0] smalt.c:344 ERROR: could not open file
[REAPR smaltmap] Error in system call:
/usr/src/app/code/Reapr_1.0.18_for_Evaldna/src/smalt index -k 13 -s 2
out_reapr_../results/flye.bam.tmp.1089.smaltmap.smalt_index
../results/flye.facheck.fa
[REAPR preprocess] Cannot find file 'out_reapr_../results/flye.bam'. Aborting
Traceback (most recent call last):
  File "EvalDNA_v1.1.py", line 467, in <module>
    runReapr()
  File "EvalDNA_v1.1.py", line 183, in runReapr
    os.chdir("./" + output_file + ".pipeline")
OSError: [Errno 2] No such file or directory: './../results/flye.pipeline'

"out_reapr_../" part looks wrong to me.

**Comment by bioinfoMMS** [comment]
Yes I believe that 'out_reper_../' is causing the problems. Can you send me your python commad? The one that should be like: 'python EvalDNA_v1.1.py -i data/inputfile.fa -o outputfile_prefix -c data/configfile.txt'

**Comment by kazumaxneo** [comment]
Thank you.
I pulled official docker image. Then, I typed following command.

$ git clone https://github.com/bioinfoMMS/EvalDNA.git && cd EvalDNA/EvalDNA_v1.1/
$ mkdir results
$ docker run -it -u $(id -u):$(id -g) -v $PWD/results:/usr/src/app/results -v $PWD/code:/usr/src/app/code -v $PWD/data:/usr/src/app/data --cpus="16" bioinfomms/evaldna
$ cd code/
$ python EvalDNA_v1.1.py -i ../data/assembly.fasta -o ../results/outprefix -c ../data/config.txt

**Comment by bioinfoMMS** [comment]
For the '-o' option in the Python command, you do not need to specify the path. So  it should just be '-o outprefix' or whatever you want to use as the prefix in the output file names. Let me know if changing that works.

**Comment by kazumaxneo** [comment]
Thanks.
After fixing the output part, I ran the command again.
$ cd code/
$ rm -rf results && mkdir results
$ python EvalDNA_v1.1.py -i ../data/assembly.fasta -o outprefix -c ../data/config.txt

But I get the same error
![1](https://user-images.githubusercontent.com/20102961/146223392-72a604af-79e7-419f-8b77-9800eac6708a.png)
.

**Comment by bioinfoMMS** [comment]
You are getting the same error, but for a different reason now. The error seems to begin a few lines from the bottom where it says 'ERROR: wrong FASTQ/FASTA format'. It looks like your reads are compressed, while EvalDNA is expecting uncompressed reads. Try it on the unzipped FQ files and let me know if that fixes it?

**Comment by kazumaxneo** [comment]
Oh, I was wrong.
After unzipping fastq, I fixed the file name in the config and ran it, and the console didn't give me the error immediately.
$ rm -rf results && mkdir results
$ python EvalDNA_v1.1.py -i ../data/assembly.fasta -o outprefix -c ../data/config.txt

But a few minutes later, I got the following error
![2](https://user-images.githubusercontent.com/20102961/146227436-15f69ece-aa92-4b84-8493-64d85d218500.png)
.

**Comment by bioinfoMMS** [comment]
Remove 'outprefix.pipeline' before running it again. I think REAPR, which EvalDNA runs, won't write over an existing directory. I need to add this to the documentation, thanks for catching this!

**Comment by kazumaxneo** [comment]
I see. 
I'm not sure if I can run well yet, but I'll try to adjust.
Thank you very much.
